### PR TITLE
feat(message): change message parsing to use regex

### PR DESCRIPTION
**Pull request by vindard**
**Addressed:**
I updated the message parsing from fixed index selections to more dynamic selections using regex functions. 

The changes were done in such a way that most of the body of the code remains mostly unchanged. All I needed to do was reassign how the 'message' variable was created and change the index addresses in a few places.

Looking forward to results of testing!

### CODE REVIEW

**Comment by johnsBeharry** [comment]
@vindard I can't keep up with all these pull requests! You're on 🔥

**Comment by vindard** [comment]
@johnsBeharry lol, yea I was doing some research into how regex's work and I needed some place to practice 😜

**Comment by johnsBeharry** [comment]
@vindard please write a test using the built in python "unittest" module for this new function.

**Comment by johnsBeharry** [comment]
@vindard all looks good to me, now just for something stylistic could you move msg_parse to the utils module.

Reason:
1. Importing the functions in a tests will be easier if it's not in run.py with a long running process (`while True`)
2. Code inside `run.py` becomes more readable

**Comment by vindard** [comment]
I wrote up some basic tests for this PR. 

Next steps are to find a way to stick them in a separate tests folder and then have them run (nosetests module I think). After that it's then to update the CircleCi config to run against them as well.

**Comment by johnsBeharry** [comment]
> It could be confusing if we ever need to use that package later on and import anything from it. Should we reconsider that 'utils' folder name @johnsBeharry?

There will always be this kind of name clashing for modules and the online packages on PiPy since there's thousands of them already created - an alternative name would be `common` or `lib` but those are also listed on PiPy as packages so it won't solve the problem.

So I vote to leave it as is for now.

> ...I opted instead to create a new variable for the extracted list from the original message variable assigned.
>
>More "Functional"?

👌 nice one. it's good the original value can still be referenced.

**Comment by vindard** [comment]
> so I vote to leave it as is for now - if we need to use the pypi package then we can amend.

Cool I'm good with that. Just wanted to flag for attention.

One more thing @johnsBeharry. I'm not sure why, but putting our functions inside of the `tests/__init__.py` file feels a little messy. I've been reading around and it seems people more use that `init` file for making a folder part of the package and importing basic things. The naming inside `/tests` gets confusing as well since there are so many `__init__.py` files around the package. 

Could we throw those functions in another file with a different name within `/utils`? Any new name suggestions?

_p.s. after this last issue I think we'll be good for a merge. I sorted out all the other things I wanted to with with the CircleCI configs and new tests (see latest commits)_.

**Comment by johnsBeharry** [comment]
> The naming inside /tests gets confusing as well since there are so many __init__.py files around the package.

The tests folder usually follows the structure of codebase. So there would not be any name clashes with __init__.py as it should be in `test/utils/__init__.py`.

```
.
+-- utils
    +-- __init__.py
+-- another_module
    +-- __init__.py
    +-- awesome.py
+-- tests
    +-- utils
        +-- __init__.py
    +-- another_module
        +-- __init__.py
        +-- awesome.py.py
```

**Comment by vindard** [comment]
@johnsBeharry gotcha, changes made accordingly. All good to go now 🙌

**Pull request merged**
